### ISSUE TITLE
Failed to copy image

### ISSUE THREAD

**Issue by FoskyM** [RoleWong/image_clipboard#1]
### Problem
I tried to use it to copy image on `windows` but failed, the original content of the copied image is `null`.
Is it caused by reading file failed?
https://github.com/RoleWong/image_clipboard/blob/faf1499602bcd92271bde8a10049571a9721e834/windows/image_clipboard_plugin.cpp#L71-L76

### Environment
- OS: Windows 11 23H2 (10.0.22631.4169)
- Flutter: 3.24.3

### My usage
```yaml
dependencies:
  flutter:
    sdk: flutter
  image_clipboard: ^1.1.0+1
```
```dart
final imageClipboard = ImageClipboard();
await imageClipboard.copyImage(filePath);
```
`filePath` is like `C:\Users\Administrator\Documents\XXX\data\test1\775dd8885a2a0b4c.jpg`
